#!/bin/bash

EDITOR=vim
TASKBIN=task
VIEWER=cat

# FOLDER to store notes in. Must already exist.
# If you sync tasks, FOLDER should be a location that syncs and is available to
# other computers, i.e. ~/dropbox/tasknotes
FOLDER="/home/batan/.task/notes/"

# Check for existence of $FOLDER
if [ ! -d $FOLDER ]; then
	echo    "Notes folder '$FOLDER' does not exist."
	echo -n "Shall I create it (y/n)? "
	read answer
	if [ $answer == "y" ]; then
	  echo "Creating '$FOLDER'."
	  mkdir -p $FOLDER;
	else
	  echo "Did NOT create $FOLDER. Exiting."
	  exit 1;
	fi
fi

# Preferred extension for tasknotes
EXT=".wiki"

# Message that gets annotated to the task to indicate that notes exist
NOTEMSG="See Notes File"

# Display usage if task number not supplied on cli
if [ $# -lt 1 -o $# -gt 2 ]; then
	echo "Usage:"
   	echo "  New/Edit note: $0 <id>"
	echo "  View note:     $0 <id> v"
	exit 1
fi

#find UUID from given task
uuid=`$TASKBIN $1 uuids`

# build full path & file name to store notes in
folder=`echo $FOLDER | sed "s|^~|$HOME|"`
file="$folder$uuid$EXT"

# determine if notes file already exists
fileexists=0
if [ -f $file ]; then
  fileexists=1
fi

# Display note if requested and exit
if [ $# -gt 1 ]; then
	if [ $fileexists = 1 ]; then
		$SHELL -c "$VIEWER $file"
	else
		echo "File not found"
	fi
	exit 1
fi

#create/edit $file with editor
$SHELL -c "$EDITOR $file"

# Create a note message representing the first line of
# the edited note file.
if [ -f $file ]; then
  NOTEMSG="[tasknote] `head -1 $file`"
  # remove any previous annotation - we want only a single
  # tasknote annotation. Detection works through the
  # [tasknote] annotation prefix
  $SHELL -c "$TASKBIN $* denotate \"[tasknote]\""
  $SHELL -c "$TASKBIN $* annotate '$NOTEMSG'"
fi

exit 0
